# -*- coding: utf-8 -*-
"""yolov6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNayZJ3WW6e85kzqZ6zd2XA4zRaZNj14
"""



!git clone https://github.com/meituan/YOLOv6

# Commented out IPython magic to ensure Python compatibility.
# %cd YOLOv6/

pip install -r requirements.txt

!python tools/infer.py --source /content/ducks.jpg --weights yolov6s.pt --conf 0.4

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.imread("runs/inference/exp/ducks.jpg")
height, width = image.shape[:2]
resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

fig = plt.gcf()
fig.set_size_inches(18, 10)
plt.axis("off")
plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
plt.show()



!python tools/infer.py --source /content/people.png --weights yolov6s.pt --conf 0.4

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.imread("runs/inference/exp/people.png")
height, width = image.shape[:2]
resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

fig = plt.gcf()
fig.set_size_inches(18, 10)
plt.axis("off")
plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
plt.show()

!python tools/infer.py --source /content/traffic2.jpg --weights yolov6s.pt --conf 0.4

# Commented out IPython magic to ensure Python compatibility.
import cv2
import matplotlib.pyplot as plt
# %matplotlib inline

image = cv2.imread("runs/inference/exp/traffic2.jpg")
height, width = image.shape[:2]
resized_image = cv2.resize(image,(3*width, 3*height), interpolation = cv2.INTER_CUBIC)

fig = plt.gcf()
fig.set_size_inches(18, 10)
plt.axis("off")
plt.imshow(cv2.cvtColor(resized_image, cv2.COLOR_BGR2RGB))
plt.show()